name: Bug report
description: File an issue about something that is not working as expected.
title: "BUG: <TITLE>"
labels: ["bug 🐛"]

body:
  - type: input
    id: version
    attributes:
      label: Action version
      description: Which version of the Control API action are you using?
      placeholder: ex. v0.1.4
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Workflow link
      description: In case of a public repository, please provide a link to the workflow file.
      placeholder: ex. https://github.com/ably-labs/ably-control-api-action/blob/main/.github/workflows/all_inputs_test.yml
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the actual behavior and the expected behavior.
      placeholder: |
        ### Actual behavior
        ex. No API key was created.
        ### Expected behavior
        ex. An API keys was created.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for your report!
