name: Feature Request
description: Request a new feature you like to see implemented.
title: "FEATURE: <TITLE>"
labels: ["feature 🎁"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the new feature. Provide as much context as possible.
      placeholder: ex. Ability to do API key rotation on a configurable interval.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for your request!
